# Generated by Django 3.1.5 on 2021-01-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breyta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bitcoin',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ethereum',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='litecoin',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='xrp',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
