# Generated by Django 3.1.5 on 2021-01-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breyta', '0002_auto_20210129_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
