# Generated by Django 3.1.5 on 2021-01-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breyta', '0003_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
